//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIX.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UIX.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Alpha channel.
        /// </summary>
        public static string Debug_Image_Overlay_A {
            get {
                return ResourceManager.GetString("Debug_Image_Overlay_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Blue channel.
        /// </summary>
        public static string Debug_Image_Overlay_B {
            get {
                return ResourceManager.GetString("Debug_Image_Overlay_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Green channel.
        /// </summary>
        public static string Debug_Image_Overlay_G {
            get {
                return ResourceManager.GetString("Debug_Image_Overlay_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock the viewport to the full image.
        /// </summary>
        public static string Debug_Image_Overlay_LockToContent {
            get {
                return ResourceManager.GetString("Debug_Image_Overlay_LockToContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color settings.
        /// </summary>
        public static string Debug_Image_Overlay_Palette {
            get {
                return ResourceManager.GetString("Debug_Image_Overlay_Palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Red channel.
        /// </summary>
        public static string Debug_Image_Overlay_R {
            get {
                return ResourceManager.GetString("Debug_Image_Overlay_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render image in SRGB.
        /// </summary>
        public static string Debug_Image_Overlay_SRGB {
            get {
                return ResourceManager.GetString("Debug_Image_Overlay_SRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        public static string Workspace_Configuration_Debug_Description {
            get {
                return ResourceManager.GetString("Workspace_Configuration_Debug_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Workspace_Configuration_Debug_Name {
            get {
                return ResourceManager.GetString("Workspace_Configuration_Debug_Name", resourceCulture);
            }
        }
    }
}
